do_email_send_test: yes
create_reports: yes

postfix_global_options:

  # Example: How to add custom Postfix options
  #          (put this into your Playbook vars):
  #  - postfix_extra_options:
  #    line_length_limit: 4096

  # Example: How to set post aliases
  #          (put this into your Playbook vars):
  #  - post_aliases:
  #    - { user: "{{ ansible_env.USER }}",
  #        alias: "{{ ansible_fqdn }}+{{ ansible_env.USER }}@example.com"}

  smtpd_banner: $myhostname ESMTP
  biff: "no"
  readme_directory: "no"
  append_dot_mydomain: "no"
  delay_warning_time: 1h
  recipient_delimiter: +

  alias_maps: hash:/etc/aliases
  alias_database: hash:/etc/aliases

  mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128

  # SMTP SSL
  smtp_tls_session_cache_database: btree:${data_directory}/smtp_scache
  smtp_tls_security_level: may
  smtp_tls_protocols: "!SSLv2, !SSLv3"

  # apple mail may send very long lines:
  line_length_limit: 2048

  # try the OS' host name lookup mechanism before failing
  smtp_host_lookup: dns, native

postfix_extra_smtpd_milters: []
postfix_extra_non_smtpd_milters: []

# use $ opendkim-genkey -b BITS -h rsa-sha256 -r -s YYYYMM -d DOMAIN -v
#   where BITS>=4096 and YYYYMM and DOMAIN replaced accordingly
postfix_dkim_keys: {}
#  example.com:
#    selector: YYYYMM
#    privatekey: |
#      -----BEGIN RSA PRIVATE KEY-----
#      …
#      -----END RSA PRIVATE KEY-----

postfix_dkim_keytable: /etc/opendkim.keytable
postfix_dkim_signingtable: /etc/opendkim.signingtable
postfix_dkim_trusted_list: /etc/opendkim.trusted
